### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by Angelika-Kurthen** [Angelika-Kurthen/SouthwestDesertMetacommunities#1]
[Aquatic Insect Community Structuring in Desert Streams,.pptx](https://github.com/Angelika-Kurthen/SouthwestDesertMetacommunities/files/5309456/Aquatic.Insect.Community.Structuring.in.Desert.Streams.pptx)

**Comment by Juniper41** [comment]
Your presentation was very clean and concise, I think your goal for this term is very interesting and manageable, good luck!

**Comment by howardre** [comment]
This was very thorough and it sounds like you have a very good idea of what you're trying to produce and what you can accomplish this quarter.

**Comment by jwongala** [comment]
I enjoyed hearing about your project and aquatic insects. You can tell you really thought about your timeline, project, and challenges a lot. Great job!

**Comment by McLeodMJ** [comment]
Hi Angelika! Great presentation, I like the idea of a color gradient map for the flow days, it will be helpful to visualize the changes. You have timely, reasonable goals and I look forward to seeing it!

**Comment by zechmeunier** [comment]
Sounds like this class will be really useful for you! Making a map in R is actually easier than you might expect; the package ggmap is super useful.

**Comment by breshears-logan** [comment]
Good work with you presentation. Have you looked at creating a DEM or a water surface model in GIS to map and show the water permanence gradients, and how they change at different times of the year? Look at the CHaMP habitat program, and that could give you some more clarity.

**Comment by Coffee-Powered-Scientist** [comment]
Nice presentation, your field is far out of my skill set but it seems like you'd benefit from a GIS veteran.

**Comment by jessealaney** [comment]
Fascinating project. I share your research interests in diversity gradients, as well as your challenges with version control! Organizing multiple datasets is an issue for me too, as mine also come from many different authors.  I look forward to seeing what works for you and sharing best practices and methods.

**Comment by JenningsJC** [comment]
You made good points about the open-data movement and trends in science collaboration. I would be interested in how you deal with sub-setting data by taxa for analyses.
