### ISSUE TITLE
Project Progress Report

### ISSUE THREAD

**Issue by Angelika-Kurthen** [Angelika-Kurthen/SouthwestDesertMetacommunities#2]
[AquaticInsectCommunityDesertStreamsReport.pptx](https://github.com/Angelika-Kurthen/SouthwestDesertMetacommunities/files/5479012/AquaticInsectCommunityDesertStreamsReport.pptx)

**Comment by Juniper41** [comment]
Your workflow looks great! Very organized and not over saturated. Looks like you are making great progress!

**Comment by howardre** [comment]
I really like that you've baked in the ability to change your research plan in your workflow based on things that will come up in the future

**Comment by McLeodMJ** [comment]
Hi Angelika! Thanks for explaining the different methods for calculating zero flow days, I'm not familiar with it and found it to be very informative. Great idea to reuse your goal slide to revisit it and address where you are now. Data processing always takes more time than we want, so great job so far. I hope you find your ER data!

**Comment by zechmeunier** [comment]
I like the notion of a "choose your own adventure" workflow haha. Good explanation of how variable your workflow has been!

**Comment by jwongala** [comment]
Your workflow diagram was really interesting, and I appreciated its flexibility.

**Comment by Coffee-Powered-Scientist** [comment]
Hi Angelika, on determining 0 flow days, is 0 flow represented by a calculation you have yet to complete or an already distinct set of points stored in your data?

**Comment by jessealaney** [comment]
Seems like you have a good roadmap in terms of goals and your workflow! Sounds like missing data is a challenge! I hope it works out! Happy to talk about sourcing functions via a master script.
